apiVersion: v1
kind: Service
metadata:
  name: namitcapstoneprj
#  namespace: eks-capstone-ns
  labels:
    app: namitcapstoneprj
spec:
  type: LoadBalancer
  selector:
    app: namitcapstoneprj
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
